library(shiny)
library(shinydashboard)
library(shinythemes)
library(ggplot2)
library(dplyr)
library(plotly)
library(d3heatmap)
library(readr)
library(stats)
library(shinyjs)
library(nipals)
library(pls)
library(tidyr)
library(MASS)
library(car)
library(rgl)
library(contoureR)
options(warn = -1)
options(shiny.maxRequestSize = 30 * 1024 ^ 2)
